# Generated by Django 5.2.3 on 2025-06-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_longa',
        ),
    ]
