# Generated by Django 5.2.3 on 2025-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_produto_descricao_longa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_roupa',
            field=models.CharField(blank=True, choices=[('eletronicos', 'Eletrônicos'), ('roupas', 'Roupas'), ('livros', 'Livros'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], help_text="Opcional. Usado apenas para produtos da categoria 'roupas'.", max_length=20, null=True),
        ),
    ]
