# Generated by Django 5.2.3 on 2025-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
