# Generated by Django 5.2.3 on 2025-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_tipo_roupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_roupa',
            field=models.CharField(blank=True, choices=[('camisa', 'Camisa'), ('blusa', 'Blusa de Frio'), ('short', 'Short'), ('calçados', 'Calçados'), ('vestido', 'Vestido'), ('jaqueta', 'Jaqueta'), ('tenis', 'Tênis'), ('outro', 'Outro')], help_text='Preencha apenas se a categoria for Roupas.', max_length=50, null=True),
        ),
    ]
