# Generated by Django 5.2.3 on 2025-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_pedido_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
