# Generated by Django 5.2.3 on 2025-06-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produto_tipo_roupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_acessorio',
            field=models.CharField(blank=True, choices=[('pulseira', 'Pulseira'), ('relogio', 'Relógio'), ('oculos', 'Óculos'), ('boné', 'Boné'), ('mochila', 'Mochila'), ('bolsa', 'Bolsa'), ('colar', 'Colar'), ('brinco', 'Brinco'), ('cinto', 'Cinto'), ('outro', 'Outro')], help_text='Preencha apenas se o produto se encaixar nesse quadro(relógio, pulseira, etc...)', max_length=50, null=True),
        ),
    ]
