# Generated by Django 5.2.3 on 2025-06-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produto_tipo_acessorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
