# Generated by Django 5.2.3 on 2025-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
