# Generated by Django 5.2.3 on 2025-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_produto_caracteristicas_produto_descricao_longa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupas', 'Roupas'), ('livros', 'Livros'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
