# Generated by Django 5.2.3 on 2025-07-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_caracteristica_produtocaracteristica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocaracteristica',
            name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='produtocaracteristica',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Caracteristica',
        ),
        migrations.DeleteModel(
            name='ProdutoCaracteristica',
        ),
    ]
