# Generated by Django 5.2.3 on 2025-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_produtocaracteristica_caracteristica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adicione somente se for aplicar um desconto para este produto.', max_digits=10, null=True, verbose_name='Preço com Desconto'),
        ),
    ]
